config/routes.rb
Rails.application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users

	# root 'products#index'
  resources :products do
		resources :order_items		
	end

	resource :cart
	resources :orders

	get 'pages/info'
	root 'pages#home'

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/cart.rb
class Cart < ApplicationRecord
	has_many :order_items, dependent: :destroy
	belongs_to :user
	has_one :order, dependent: :destroy

	default_scope {order(created_at: :desc)}

	def total_quantity
		@count = 0

		order_items.all.each do |item|
			@count = @count + item.quantity
		end

		@count
	end

	def total_price
		@total_price = 0

		order_items.all.each do |item|
			@total_price += item.product.price * item.quantity
		end

		@total_price
	end

	def total_price_in_usd
		total_price / 100
	end

end

app/models/order.rb
class Order < ApplicationRecord
	has_many :order_items
	belongs_to :cart
	belongs_to :user

	validates :first_name, presence: true
	validates :last_name, presence: true
	validates :email, presence: true
	validates :address_1, presence: true
	validates :city, presence: true
	validates :country, presence: true

	def save_and_charge
		if self.valid?
			Stripe::Charge.create(
				amount: self.total_value.to_i,
				currency: "inr",
				source: self.stripe_token,
				description: "Order for #{self.email} of amount $#{self.total_value}"
			)
			self.save
		else
			false
		end
	rescue Stripe::CardError => e
		@message = e.json_body[:error][:message]
		self.errors.add(:stripe_error, @message)
	end

	def get_items
		cart.order_items
	end

	def total_value
		@total_price = 0

		get_items.each do |item|
			@total_price += item.product.price * item.quantity
		end

		@total_price
	end

end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  belongs_to :product
	
  # belongs_to :order, optional: true
  belongs_to :cart, optional: true
end

app/models/product.rb
class Product < ApplicationRecord

	has_many :order_items, dependent: :destroy
	
	validates :title, presence: true
	validates :description, presence: true
	validates :price, presence: true
	
	mount_uploader :image_1, ProductImageUploader
	mount_uploader :image_2, ProductImageUploader
	mount_uploader :image_3, ProductImageUploader
	mount_uploader :image_4, ProductImageUploader
	mount_uploader :image_5, ProductImageUploader

	def number_to_usd
		price / 100
	end
	
end

app/models/user.rb
class User < ApplicationRecord
	has_many :carts
	has_many :orders
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	protect_from_forgery with: :exception

	before_action :configure_permitted_parameters, if: :devise_controller?
	
	before_action :current_cart
	helper_method :current_cart


	def current_cart
		if user_signed_in?

			cart = Cart.find_by(user: current_user)

			if cart.nil?
				@current_cart = Cart.create(user: current_user)
				puts "Cart is nil"
			else
				@current_cart = cart
				puts "cart is not nil"
			end

		end

	end	

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:user_name, :first_name, :last_name, :phone_number, :address, :password])
    devise_parameter_sanitizer.permit(:account_update, keys: [:user_name, :first_name, :last_name, :phone_number, :address, :password, :password_confirmation, :current_password])
  end

	# Prevent CSRF attacks by raising an exception.
	# For APIs, you may want to use :null_session instead.

	# before_action :configure_permitted_parameters, if: :devise_controller?

	# protected

	# def configure_permitted_parameters
	# 	devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:email, :password, :user_name, :first_name, :last_name, :phone_number, :address) }
	# 	devise_parameter_sanitizer.for(:account_update) { |u| u.permit(:name, :email, :password, :current_password, :user_name, :first_name, :last_name, :phone_number, :address) }
	# end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController



	def show
		unless user_signed_in?
			flash[:error] = "Please Login or Signup"
			redirect_to root_path
		else
			@order_items = OrderItem.includes(:product).where(cart_id: @current_cart.id)
		end
	end

end

app/controllers/order_items_controller.rb
class OrderItemsController < ApplicationController	
	def create
		@product = Product.find(params[:product_id])
		@quantity = form_params[:quantity]
		@current_cart.order_items.create(product: @product, quantity: @quantity)
		flash[:success] = "Product successfully added to your cart"
		redirect_to product_path(@product)
	end

	def update
		@product = Product.find(params[:product_id])
		@order_item = OrderItem.find_by(id: params[:id], cart: @current_cart)
		@order_item.update(form_params)
		flash[:success] = "Your cart has been updated successfully"
		redirect_to product_path(@product)
	end

	def destroy
		@product = Product.find(params[:product_id])
		@current_cart.order_items.where(product: @product).destroy_all
		redirect_to @current_cart
	end

	private
	
	def form_params
		params.require(:order_item).permit(:quantity)
	end

end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController

	before_action :require_login

	def index
		@orders = current_user.orders.order(created_at: :desc)
	end

	def new
		@order = Order.new
	end


	def show
		@order = Order.find(params[:id])
	end

	def create

		@order = Order.new(form_params)
		@order.user = current_user
		@order.cart = @current_cart
		
		if @order.save_and_charge && @order.errors.blank?

			OrderMailer.invoice(@order).deliver_now
			
			new_cart = Cart.new(user: current_user)

			if new_cart.save
				@current_cart = new_cart
				flash[:success] = "Success! Your Order Has Been Confirmed"
				redirect_to root_path
			else
				flash[:error] = "Oops, Error while saving cart"
			end
		else 
			flash[:error] = "Oops, something went wrong, Please try again"
			render :new
		end
			
	end 

	def require_login
		unless user_signed_in?
			flash[:error] = "Please Login or Signup"
			redirect_to root_path
		end
	end

	private

	def form_params
		params.require(:order).permit(:first_name, :last_name, :email, :country, :address_1, :address_2, :city, :postal_code, :stripe_token)
	end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
	def info
		
	end

	def home
		@featured_products = Product.where(is_featured: true)
	end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
		@products = Product.all
  end

  def show
		@product = Product.find(params[:id])

		@order_items = @product.order_items.find_by(product: @product, cart: @current_cart)

		if @order_items.nil?
			@order_items = @product.order_items.new(product: @product, quantity: 1)
		end
  end
	
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/order_items_helper.rb
module OrderItemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/carts/show.html.erb
<% if user_signed_in? %>
	<% if @current_cart.order_items.any? %>
		<table width="80%">
			<thead>
				<tr>
					<th></th>
					<th>Item</th>
					<th>Price</th>
					<th>Quantity</th>
				</tr>
			</thead>
			<tbody>
				<% @current_cart.order_items.each do |item| %>
					<tr>
						<th width="10%">
							<%= image_tag item.product.image_1.thumb.url %>
						</th>
						<th width="20%">
							<%= item.product.title %>
						</th>
						<th width="10%"><%= number_to_currency item.product.number_to_usd %></th>
						<th width="30%">
							<%= simple_form_for [item.product, item] do |f| %>
								<%= f.input :quantity, label: false %>
								<%= f.button :submit, "Update Quantity" %>
							<% end %>
						</th>
						<th width="20%"><%= link_to "Remove", product_order_item_path(item.product, item), data: {turbo_method: :delete, turbo_confirm: "Are you sure to remove #{item.product.title} from the cart?"} %></th>
					</tr>
				<% end %>
			</tbody>
		</table>
		<h3> <%= number_to_currency @current_cart.total_price_in_usd %> </h3>
		<%= link_to "Cotinue to Checkout", new_order_path %>
	<% else %>
		<h3>Your cart is empty</h3>
	<% end %>



<% else %>
	<p>Kindly <%= link_to "LogIn", new_user_session_path %> or <%=link_to "SignUp", new_user_registration_path %> to purchase any item</p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AnotherPin</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
		<script src="https://js.stripe.com/v3/"></script>
  </head>

  <body>
		<header>
			<div class="logo">
				<h1><%= link_to "Another Pin Co.", root_path %></h1>
			</div>
			<div class="nav">
				<p>
					<%= link_to "Shop", products_path %>&nbsp;&nbsp;&nbsp;&nbsp;
					<%= link_to "Info", pages_info_path %>&nbsp;&nbsp;&nbsp;&nbsp;
					<% if user_signed_in? %>
						<%= link_to "Cart", cart_path %>&nbsp;&nbsp;&nbsp;&nbsp;
						<% if current_user.orders.any? %>
							<%= link_to "Order", orders_path %>&nbsp;&nbsp;&nbsp;&nbsp;
						<% end %>
						<%= link_to "Log Out", destroy_user_session_path, method: :delete %>&nbsp;&nbsp;&nbsp;&nbsp;
						<%= link_to "Edit Profile", edit_user_registration_path %>&nbsp;&nbsp;&nbsp;&nbsp;
					<% else %>
						<%= link_to "Sign Up", new_user_registration_path %>&nbsp;&nbsp;&nbsp;&nbsp;
						<%= link_to "Log In", new_user_session_path %>&nbsp;&nbsp;&nbsp;&nbsp;
					<% end %>
					</p>
			</div>
		</header>
		<% if flash[:success].present? %>
			<div class="flash-success"><p><%= flash[:success] %></p></div>
		<% elsif flash[:error].present? %>
			<div class="flash-error"><p><%= flash[:error] %></p></div>
	  <% end %>
		<p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/orders/index.html.erb
<% @orders.each do |order| %>

	<h3><%= link_to order.id, order_path(order) %></h3>

	<% order.cart&.order_items .each do |item| %>
		<h3><%= item.product.title %> </h3>
		<h4>Quantity: <%= item.quantity %> (<%= item.product.price %>/q)</h4>
		<hr>
	<% end %>

	<hr>

<% end %>

app/views/orders/new.html.erb
<h1>Checkout</h1>

<p>Order Items: <%= @current_cart.order_items.size %></p>

<%= simple_form_for @order do |f| %>
	<%= f.input :first_name %>
	<%= f.input :last_name %>
	<%= f.input :email %>
	<%= f.input :country %>
	<%= f.input :address_1 %>
	<%= f.input :address_2 %>
	<%= f.input :city %>
	<%= f.input :postal_code %>

	<div id="card-errors">
		<% @order.errors[:stripe_error].each do |message| %>
			<p><%= message %></p>
		<% end %>
	</div>
	<div id="card"></div>
	<%= f.button :submit, "Submit Order" %>
<% end %>

<script>

	var stripe = Stripe("<%= Rails.application.credentials[Rails.env.to_sym][:stripe_public_key] %>");
	var elements = stripe.elements();
	var card = elements.create("card", {hidePostalCode: true});

	card.mount("#card");
	var form = document.getElementById('new_order');


		 form.addEventListener('submit', function(event) {
      $('#submit-stripe').prop('disabled', true);
      event.preventDefault();
      stripe.createToken(card).then(function(result) {
        if (result.error) {
          var errorElement = document.getElementById('card-errors');
          errorElement.textContent = result.error.message;
					console.log(result.error.message);
        } else {

					console.log(result.token);
					var token = document.createElement("input");
							token.setAttribute("type", "hidden");
							token.setAttribute("name", "order[stripe_token]");
							token.setAttribute("value", result.token.id);

          document.getElementById("new_order").appendChild(token);
          form.submit();
        }
      });
	})
</script>

app/views/orders/show.html.erb
<%# <h2>Thank You</h2>
<p>Your order has been received</p> %>
<%# <%= link_to "Back to Home", root_path %> %>


<% @order.cart.order_items .each do |item| %>
	<h3><%= item.product.title %> </h3>
	
	<h4>Quantity: <%= item.quantity %> (<%= item.product.price %>/q)</h4>
	<hr>
<% end %>

app/views/orders/thank_you.html.erb
<h2>Thank You</h2>
<h3>Your Order Has Been Confirmed</h3>
<br>
<br>
<h3><%= link_to "Back To Home", root_path %></h3>

app/views/pages/home.html.erb
<h2>Featured Pins</h2>
<p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Totam aspernatur numquam rem quam perferendis ratione earum possimus fugiat soluta doloribus?</p>

<%= render partial: "products/product", collection: @featured_products %>

app/views/pages/info.html.erb
<h2>Another Pin Inc.</h2>
<p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Possimus dolorem natus iure quam nulla consectetur explicabo officia, soluta pariatur commodi, ex quisquam consequatur rerum? Minima doloremque rem itaque natus non. </p>
<p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Architecto debitis numquam dolorum nesciunt consequuntur provident quidem officiis, eos quam sunt magnam nulla sit alias illum, fugiat optio neque minus enim? Dolorem inventore ducimus dolor impedit aspernatur maxime voluptatibus cum quo modi illo necessitatibus earum ut reiciendis qui sunt quia ipsam doloribus repellat reprehenderit, error nobis sequi. Qui iste nesciunt aut odio, perspiciatis voluptas magnam dolorem odit possimus rem accusamus quo nostrum culpa consectetur sunt molestias laudantium quod delectus rerum deleniti quia ipsum quasi? Ea provident dolor, facilis qui eos a fugit nisi veniam consequuntur quam, natus optio accusamus porro commodi?</p>

app/views/products/_product.html.erb
<div class="product">
	<div>
		<%= link_to product_path(product) do %>
			<%= image_tag product.image_1.medium.url %>
		<% end %>
		<h3><%= link_to product.title, product_path(product) %> </h3>
		<p> <%= number_to_currency product.number_to_usd %> </p>
	</div>
</div>

app/views/products/index.html.erb
<h2>All Collection</h2>

<%= render partial: "product", collection: @products %>

app/views/products/show.html.erb
<h2><%= @product.title %></h2>
<p><%= simple_format @product.description %> </p>

<%= image_tag @product.image_1.thumb.url %>
<%= image_tag @product.image_2.thumb.url %>
<h4>&#8377; <%= @product.number_to_usd %> </h4>
<% if user_signed_in? %>
	<%= simple_form_for [@product, @order_items] do |f| %>
		<%= f.input :quantity %>
		<%= f.button :submit, "Add to Cart" %>
	<% end %>
<% else %>
	<p><%= link_to "Log In", new_user_session_path %> to purchase this product</p>
<% end %>